In [1]:
import numpy as np

In [2]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
ar1 = np.array([1,3,5])

In [4]:
print(m1)
print(ar1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 3 5]


In [5]:
print(m1 @ ar1)

[22 49 76]


In [6]:
print(m1.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
print(type(m1))

<class 'numpy.ndarray'>
